'use strict';
/* Pure gear/chip fallback for chests. Weapon trait offers are generated by weapon-traits.js. */
(function(root){
function selectChestChoices({room,player,chipCatalog,seed,hash,randomGear}){
 const choices=[],gearRoom=player.gearBag.length<20;
 const chipIds=Object.keys(chipCatalog).filter(id=>!player.chipBag.includes(id)&&!Object.values(player.chips||{}).includes(id));
 if((room.type==='elite'||room.reward==='chip')&&player.chipBag.length<15&&chipIds.length){
  for(let c=0;c<3&&chipIds.length;c++){
   const index=hash(room.x,room.y,seed+room.id*41+c*773)%chipIds.length;
   choices.push({type:'chip',id:chipIds.splice(index,1)[0]});
  }
 }else if(gearRoom){
  const offered=new Set();
  for(let attempt=0;choices.length<3&&attempt<40;attempt++){
   const piece=randomGear(()=>Math.abs(Math.sin(seed+room.id*97+attempt*313)));
   if(!piece||!piece.id||offered.has(piece.id))continue;
   offered.add(piece.id);
   choices.push({type:'gear',...piece});
  }
 }
 return choices;
}
root.DropForgeChestRewards=Object.freeze({selectChestChoices});
})(window);
