'use strict';
/* Enemy movement, support, evasion and attacks; host supplies live game state and effects. */
(function(root){
function createEnemyUpdate({getGame,W,FLOOR,GRAVITY,clamp,burst,floating,sound,killEnemy,floorPhysics,damagePlayer,hitGenerator,collideRect,spawnEnemy}){
function enemyUpdate(e,room,dt){
 if(!e.alive)return;if(e.burnTime>0){e.burnTime=Math.max(0,e.burnTime-dt);e.burnTick=(e.burnTick||.5)-dt;if(e.burnTick<=0){e.burnTick+=.5;const burn=e.burnDamage||1,absorbed=Math.min(e.shield||0,burn);e.shield=(e.shield||0)-absorbed;e.hp-=burn-absorbed;e.hit=.09;floating(e.x+e.w/2,e.y-12,'YANMA '+(e.burnDamage||1),'#ffb273');if(e.hp<=0){killEnemy(room,e);return;}}}const game=getGame(),p=game.player,threat=room.threatLevel||0,moveBoost=1+threat*.12,attackBoost=1+threat*.10;e.teleportCd=Math.max(0,e.teleportCd-dt);e.healPulse=Math.max(0,e.healPulse-dt);e.hit=Math.max(0,e.hit-dt);e.phase+=dt;e.markTime=Math.max(0,(e.markTime||0)-dt);e.hunterMarkTime=Math.max(0,(e.hunterMarkTime||0)-dt);e.cryoSlowTime=Math.max(0,(e.cryoSlowTime||0)-dt);e.freezeTime=Math.max(0,(e.freezeTime||0)-dt);if(e.freezeTime>0){e.vx=0;return;}e.dodgeCd=Math.max(0,e.dodgeCd-dt);e.dodgeTime=Math.max(0,e.dodgeTime-dt);e.stagger=Math.max(0,(e.stagger||0)-dt);e.aiJump-=dt;e.dropThrough=Math.max(0,(e.dropThrough||0)-dt);if(e.type==='red'||e.type==='boss')e.chargeCooldown=Math.max(0,(e.chargeCooldown||0)-dt);if(e.type==='boss')e.summonCooldown=Math.max(0,(e.summonCooldown||0)-dt);
 const targetGenerator=room.generator&&!room.generator.failed&&room.generator.time>0&&e.type==='red'?room.generator:null;const dx=(targetGenerator?targetGenerator.x:p.x+p.w/2)-(e.x+e.w/2),dy=(targetGenerator?targetGenerator.y-18:p.y+p.h/2)-(e.y+e.h/2),dist=Math.abs(dx);
 // Dodge only when a bullet is approaching: 10-second per-enemy cooldown.
 if(e.dodgeCd<=0&&!(e.type==='red'&&(e.chargeWindup>0||e.chargeTime>0))){const threat=game.bullets.find(b=>{const rx=e.x+e.w/2-b.x,ry=e.y+e.h/2-b.y,closing=(rx*b.vx+ry*b.vy)>0,d=Math.hypot(rx,ry),cross=Math.abs(rx*b.vy-ry*b.vx)/(Math.hypot(b.vx,b.vy)||1);return closing&&d<200&&cross<e.h*.65+20;});if(threat){e.dodgeCd=10;e.dodgeTime=e.type==='blue'?.34:.26;e.dodgeDir=Math.random()<.5?-1:1;if(e.type==='blue')e.vy=-e.dodgeDir*440;else {e.vy=-470;e.grounded=false;}burst(room,e.x+e.w/2,e.y+e.h/2,'#bdefff',12,185);floating(e.x,e.y-22,'DODGE','#a3edff');sound(630,.08,'triangle',.018);}}
 if(e.type==='warlock'){e.summonCooldown-=dt;const active=room.enemies.filter(a=>a.alive&&a.summoner===e).length;if(e.summonCooldown<=0&&active<2&&room.enemies.length<(room.enemyCap||game.settings.cap)+2){const brute=spawnEnemy(room,'brute',clamp(e.x+(dx>0?75:-85),60,W-110),FLOOR-69);brute.summoner=e;e.summons++;e.summonCooldown=8;burst(room,brute.x+brute.w/2,brute.y,'#c5a3ff',17,155);floating(e.x,e.y-27,'MUHAFIZ ÇAĞIRDI','#d8c1ff');}}if(e.type==='riftcaller'){e.summonCooldown-=dt;const portal=room.portals.find(q=>q.owner===e&&q.alive);if(e.summonCooldown<=0&&!portal&&e.summons<2){const x=clamp(e.x+(dx>0?85:-85),85,W-85);room.portals.push({type:'red',biome:room.biome,x,y:FLOOR-27,produced:0,max:1,spawnLimit:3,owner:e,time:2,spawnDuration:2,alive:true,hp:115,maxHp:115,hit:0,shield:0,shieldTriggered:false,overdrive:false,regenDelay:5,regenBase:115,regenCap:115});e.summons++;e.summonCooldown=12;burst(room,x,FLOOR-27,'#8be4f5',20,170);floating(e.x,e.y-27,'GEÇİT AÇTI','#9ceeff');}}if(e.type==='healer'){const allies=room.enemies.filter(a=>a.alive&&a!==e&&a.type!=='healer'&&a.hp<a.maxHp);if(e.healPulse<=0&&allies.length){allies.sort((a,b)=>Math.hypot(a.x-e.x,a.y-e.y)-Math.hypot(b.x-e.x,b.y-e.y));const ally=allies[0];if(Math.hypot(ally.x-e.x,ally.y-e.y)<335){ally.hp=Math.min(ally.maxHp,ally.hp+14);e.healPulse=1.25;burst(room,ally.x+ally.w/2,ally.y,'#81ffbd',7,100);floating(ally.x,ally.y-22,'+14','#82ffbc');}}if(e.hit>0&&e.teleportCd<=0){e.x=clamp(e.x+(dx>0?-245:245),70,W-e.w-70);e.y=FLOOR-e.h;e.vy=-300;e.teleportCd=5;burst(room,e.x,e.y,'#8bffcb',17,150);floating(e.x,e.y-15,'IŞINLANDI','#8bffcb');}}
 if(e.type==='red'&&e.chargeWindup<=0&&e.chargeTime<=0&&e.chargeCooldown<=0&&e.grounded&&e.stagger<=0&&dist>115&&dist<590&&Math.abs(dy)<95){e.chargeWindup=.62;e.chargeDir=Math.sign(dx)||1;e.chargeHit=false;e.windup=0;e.fire=Math.max(e.fire,.9);floating(e.x+e.w/2,e.y-25,'HÜCUM!','#ffb17e');}
 if(e.type==='red'&&e.chargeWindup>0){e.chargeWindup=Math.max(0,e.chargeWindup-dt);if(e.chargeWindup===0){e.chargeTime=.48;burst(room,e.x+e.w/2,e.y+e.h/2,'#ff9c67',12,145);}}
 if(e.type==='blue'){e.vx=e.stagger>0?e.knockVx:e.dodgeTime>0?e.dodgeDir*570:clamp(dx*1.75,-245,245);e.x=clamp(e.x+e.vx*dt*moveBoost*(e.cryoSlowTime>0?.65:1),45,W-e.w-45);e.y=clamp(e.y+(e.dodgeTime>0?e.vy:Math.sin(e.phase*4.2)*38+clamp(p.y-115-e.y,-115,115))*dt*moveBoost,90,470);}
 else {if(e.stagger>0)e.vx=e.knockVx;else if(e.dodgeTime>0)e.vx=e.dodgeDir*410;else if(e.type==='boss')e.vx=dist>(e.bossStyle==='sniper'?310:e.bossStyle==='fan'?190:95)?Math.sign(dx)*73*(e.bossSpeed||1)*(e.bossPhase===2?1.35:1):e.bossStyle==='sniper'?-Math.sign(dx)*85:0;else if(e.type==='brute')e.vx=dist>42?Math.sign(dx)*67:0;else if(e.type==='warlock'||e.type==='riftcaller')e.vx=dist<300?-Math.sign(dx)*65:dist>440?Math.sign(dx)*42:0;else if(e.type==='red')e.vx=e.chargeTime>0?e.chargeDir*650:e.chargeWindup>0?0:dist>39?Math.sign(dx)*105:0;else if(e.type==='healer')e.vx=dist<320?-Math.sign(dx)*140:dist>435?Math.sign(dx)*65:0;else e.vx=dist<185?-Math.sign(dx)*83:dist>280?Math.sign(dx)*58:0;
 if(e.aiJump<=0&&e.grounded&&e.type!=='boss'&&!(e.type==='red'&&(e.chargeWindup>0||e.chargeTime>0))){const higher=room.platforms.filter(q=>q.y<e.y+e.h-45&&q.y>e.y+e.h-225&&Math.abs(q.x+q.w/2-(e.x+e.w/2))<235);if(higher.length&&(Math.random()<.58||p.y+80<e.y)){const target=higher[Math.floor(Math.random()*higher.length)];e.aiTarget=target.x+target.w/2;e.vy=-Math.sqrt(2*GRAVITY*Math.max(95,e.y+e.h-target.y+12));e.grounded=false;e.aiJump=2+Math.random()*2.5;burst(room,e.x+e.w/2,e.y+e.h,'#b6c6d7',5,80);}else e.aiJump=1.2+Math.random()*1.4;}
 if(e.aiTarget!==null&&!e.grounded&&e.chargeTime<=0)e.vx=clamp(e.aiTarget-(e.x+e.w/2),-1,1)*Math.max(Math.abs(e.vx),155);
 if(e.grounded&&e.dropThrough<=0&&p.y>e.y+e.h+85&&room.platforms.some(q=>Math.abs(e.y+e.h-q.y)<5&&e.x+e.w>q.x+5&&e.x<q.x+q.w-5)){e.dropThrough=.48;e.grounded=false;e.y+=5;e.vy=Math.max(e.vy,95);e.aiTarget=null;e.aiJump=Math.max(e.aiJump,1.1);}const enemyOldX=e.x;e.x+=e.vx*dt*(e.stagger>0?1:moveBoost)*(e.moveMultiplier||1)*(e.cryoSlowTime>0?.65:1);floorPhysics(e,dt,room.platforms,enemyOldX);if(e.grounded)e.aiTarget=null;}
 if(e.type==='red'&&e.chargeTime>0){e.chargeTime=Math.max(0,e.chargeTime-dt);if(!e.chargeHit&&collideRect(p,e)){e.chargeHit=true;if(p.invuln<=0){damagePlayer(Math.round(35*(e.damageScale||1)));p.vx=e.chargeDir*530;p.vy=-350;p.grounded=false;p.wallKick=.24;floating(p.x,p.y-30,'HÜCUM · GERİ İTME','#ff9d80');}}if(e.chargeTime===0){e.chargeCooldown=3.1;e.fire=Math.max(e.fire,.6);}}
 e.fire-=dt*(e.attackMultiplier||1)*(e.cryoSlowTime>0?.65:1);if(e.windup>0){e.windup=Math.max(0,e.windup-dt);if(e.windup===0){const ax=p.x+p.w/2-(e.x+e.w/2),ay=p.y+p.h/2-(e.y+e.h/2),ad=Math.hypot(ax,ay),aim=Math.atan2(ay,ax);if(e.type==='red'||e.type==='brute'){if(ad<90&&Math.abs(ay)<65)damagePlayer(Math.round((e.type==='brute'?29:21)*(e.damageScale||1)*(1+threat*.08)));if(room.generator&&!room.generator.failed&&e.x<room.generator.x+70&&e.x+e.w>room.generator.x-70)hitGenerator(room,10);}else{const n=e.type==='boss'?(e.bossStyle==='fan'?e.bossPhase===2?9:7:e.bossStyle==='spread'?e.bossPhase===2?7:5:e.bossStyle==='inferno'?e.bossPhase===2?8:5:e.bossStyle==='sniper'?1:e.bossStyle==='rush'?2:e.bossPhase===2?5:3):1,speed=e.type==='boss'&&e.bossStyle==='sniper'?e.bossPhase===2?640:540:e.type==='blue'?390:e.type==='purple'?270:340,g=e.aimGenerator&&room.generator&&!room.generator.failed&&room.generator.time>0?room.generator:null,fireAngle=g?Math.atan2(g.y-18-(e.y+e.h/2),g.x-(e.x+e.w/2)):aim;for(let i=0;i<n;i++){const a=fireAngle+(i-(n-1)/2)*(e.type==='boss'&&e.bossStyle==='fan'?.16:e.type==='boss'&&e.bossStyle==='inferno'?.42:.23)+(e.type==='boss'&&e.bossStyle==='inferno'?e.phase*.3:0);game.enemyBullets.push({x:e.x+e.w/2,y:e.y+e.h/2,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,life:3,damage:Math.round((e.type==='boss'?(e.bossPhase===2?20:16):e.type==='blue'?11:7)*(e.damageScale||1)*(1+threat*.08)),color:e.type==='boss'?(e.bossColor||'#ffb78c'):e.biome==='lava'?'#ff8748':e.biome==='forest'?'#93d879':e.biome==='crystal'?'#cd9dff':e.type==='blue'?'#69bdff':'#c787fa',explosive:e.type==='purple',blastRadius:e.type==='purple'?76:0,effect:e.biome});}}e.fire=(e.type==='brute'?1.5:e.type==='red'?1.05:e.type==='boss'?(e.bossStyle==='sniper'?1.5:e.bossStyle==='rush'?.8:e.bossStyle==='inferno'?.9:1.1)*(e.bossPhase===2?.65:1):e.type==='blue'?1.45:2.35)*[1,.91,.82,.74][(e.level||1)-1]/attackBoost;}}else if(e.fire<=0&&!(e.type==='red'&&(e.chargeWindup>0||e.chargeTime>0))){if(e.type==='healer')e.fire=1.4;else{e.aimGenerator=!!(room.generator&&!room.generator.failed&&room.generator.time>0&&e.type!=='boss'&&Math.floor(room.time*2+e.phase)%2===0);e.windup=e.type==='boss'?(e.bossPhase===2?.42:.62):e.type==='purple'?.6:e.type==='blue'?.42:.36;e.fire=1;}}
 if(e.type==='boss'&&e.bossStyle==='blink'&&e.teleportCd<=0){e.x=clamp(p.x+(dx>0?-150:150),65,W-e.w-65);e.teleportCd=e.bossPhase===2?2.6:4.3;burst(room,e.x+e.w/2,e.y+e.h/2,e.bossColor,15,160);}if(e.type==='boss'&&e.bossStyle==='summon'&&e.summonCooldown<=0&&room.enemies.filter(q=>q.alive&&q.summoner===e).length<(e.bossPhase===2?3:2)){const minion=spawnEnemy(room,'purple',clamp(e.x+(dx>0?110:-90),80,W-90),FLOOR-37);minion.summoner=e;e.summonCooldown=e.bossPhase===2?4.5:7;burst(room,minion.x,minion.y,e.bossColor,12,120);}if(e.type==='boss'&&e.bossStyle==='rush'&&e.chargeCooldown<=0){e.vx=Math.sign(dx)*520*(e.bossPhase===2?1.25:1);e.chargeCooldown=e.bossPhase===2?2.2:3.5;}if(collideRect(p,e)&&!(e.type==='red'&&(e.chargeWindup>0||e.chargeTime>0)))damagePlayer(Math.round((e.type==='brute'?27:e.type==='red'?20:e.type==='boss'?23:8)*(e.damageScale||1)));
}
return enemyUpdate;
}
root.DropForgeEnemyAI=Object.freeze({createEnemyUpdate});
})(window);
