'use strict';
/* Loot, chest, breakable and room prop canvas drawing. */
(function(root){
function createLootRenderer({ctx,currentRoom,ACCESSORIES,WEAPON_SPRITES,weaponName,PROJECTILE_FAMILIES}){
function drawChest(q){
 ctx.fillStyle=q.opened?'#5c4d3e':'#bd884c';ctx.fillRect(q.x-25,q.y-15,50,29);ctx.fillStyle=q.opened?'#766552':'#f8ce72';ctx.fillRect(q.x-25,q.y-20,50,9);ctx.fillRect(q.x-4,q.y-15,8,18);
 if(!q.opened&&q.grounded&&currentRoom().interact?.nearChest){ctx.fillStyle='#ffe4a9';ctx.font='bold 13px monospace';ctx.fillText('E · AÇ',q.x-24,q.y-37);}
}
function drawBreakable(b){ctx.save();ctx.fillStyle=b.hit>0?'#eaf9ff':'#4b6375';ctx.strokeStyle='#9eb5c0';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(b.x+9,b.y);ctx.lineTo(b.x+b.w-9,b.y+2);ctx.lineTo(b.x+b.w,b.y+15);ctx.lineTo(b.x+b.w-3,b.y+b.h-8);ctx.lineTo(b.x+8,b.y+b.h);ctx.lineTo(b.x,b.y+b.h-18);ctx.closePath();ctx.fill();ctx.stroke();ctx.strokeStyle='#829dab';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(b.x+b.w*.37,b.y+7);ctx.lineTo(b.x+b.w*.5,b.y+b.h*.37);ctx.lineTo(b.x+b.w*.31,b.y+b.h*.62);ctx.moveTo(b.x+b.w*.5,b.y+b.h*.37);ctx.lineTo(b.x+b.w*.79,b.y+b.h*.57);ctx.stroke();ctx.fillStyle='#a4f0e2';ctx.font='bold 10px monospace';ctx.textAlign='center';ctx.fillText('⛏ '+Math.ceil(b.hp)+' / '+b.maxHp,b.x+b.w/2,b.y-8);ctx.restore();}
function drawProp(o){ctx.save();ctx.translate(o.x,o.y);ctx.fillStyle=o.hit>0?'#ffffff':o.kind==='crystal'?'#69b6d1':'#947453';ctx.fillRect(0,0,o.w,o.h);ctx.strokeStyle=o.kind==='crystal'?'#b7f8ff':'#d2b38a';ctx.lineWidth=3;ctx.strokeRect(2,2,o.w-4,o.h-4);ctx.beginPath();ctx.moveTo(3,3);ctx.lineTo(o.w-3,o.h-3);ctx.moveTo(o.w-3,3);ctx.lineTo(3,o.h-3);ctx.stroke();ctx.restore();}
function drawLoot(item){
 ctx.save();ctx.translate(item.x,item.y);if(item.kind){if(item.kind==='gold'){ctx.shadowColor='#ffe187';ctx.shadowBlur=17;ctx.fillStyle='#ffc54d';ctx.beginPath();ctx.arc(0,0,10,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff7c9';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#765126';ctx.font='bold 13px monospace';ctx.textAlign='center';ctx.fillText('G',0,4);ctx.restore();return;}if(item.kind==='mod'){ctx.shadowColor='#f9dc85';ctx.shadowBlur=18;ctx.fillStyle='#e8c66f';ctx.fillRect(-12,-12,24,24);ctx.fillStyle='#293d57';ctx.fillRect(-7,-2,14,4);ctx.fillRect(-2,-7,4,14);ctx.restore();return;}if(item.kind==='ammo'){const family=PROJECTILE_FAMILIES[item.artifact]||PROJECTILE_FAMILIES.kinetic;ctx.shadowColor=family.color;ctx.shadowBlur=18;ctx.fillStyle=family.trail;ctx.fillRect(-14,-11,28,22);ctx.fillStyle=family.color;ctx.fillRect(-11,-8,22,16);ctx.fillStyle='#172639';ctx.font='bold 13px monospace';ctx.textAlign='center';ctx.fillText(({kinetic:'K',scatter:'S',pierce:'D',plasma:'P',laser:'L',explosive:'X',arc:'E'})[item.artifact]||'K',0,5);ctx.fillStyle='#e9f8ff';ctx.fillRect(-10,-11,20,3);ctx.restore();return;}if(item.kind==='artifact'){ctx.shadowColor='#cfa5ff';ctx.shadowBlur=18;ctx.fillStyle=ACCESSORIES[item.artifact]?.color||'#bf9aff';ctx.beginPath();ctx.moveTo(0,-16);ctx.lineTo(15,0);ctx.lineTo(0,16);ctx.lineTo(-15,0);ctx.closePath();ctx.fill();ctx.restore();return;}ctx.shadowBlur=14;ctx.shadowColor=item.kind==='health'?'#73f3a0':item.kind==='grenade'?'#ffa56f':'#ffdf89';ctx.fillStyle=item.kind==='health'?'#62dd90':item.kind==='grenade'?'#ed8c68':'#f4bf64';ctx.fillRect(-12,-12,24,24);ctx.fillStyle='#25303c';if(item.kind==='health'){ctx.fillRect(-3,-9,6,18);ctx.fillRect(-9,-3,18,6);}else if(item.kind==='grenade'){ctx.fillRect(-2,-9,4,5);ctx.fillRect(-7,-4,14,13);}else{ctx.fillRect(-7,-5,5,13);ctx.fillRect(2,-5,5,13);}ctx.restore();return;}ctx.shadowBlur=10;ctx.shadowColor='#eebf72';const img=WEAPON_SPRITES[item.weapon];if(img instanceof HTMLCanvasElement){ctx.imageSmoothingEnabled=false;ctx.drawImage(img,-29,-17,58,29);}else{ctx.fillStyle='#c2cbd6';ctx.fillRect(-20,-7,36,9);}ctx.restore();
 if(item.grounded&&currentRoom().interact?.nearbyLoot===item){ctx.fillStyle='#ffe4a9';ctx.font='bold 12px monospace';ctx.fillText('E · '+weaponName(item.weapon)+' AL',item.x-50,item.y-29);}
}
return {drawChest,drawBreakable,drawProp,drawLoot};
}
root.DropForgeLootView=Object.freeze({createLootRenderer});
})(window);
